name: StartServer

on:
  push:
    branches: [master]

jobs:
  build:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Install dependencies
        run: npm install
      - name: Add ngrok token
        run: npx ngrok authtoken ${{ secrets.NGROK_TOKEN }}
      - name: Start
        run: |
          wget https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/402/downloads/paper-1.17.1-402.jar &&
          java -jar paper-1.17.1-402.jar nogui & node src
